name: GDPR Compliance Check

on:
  pull_request:
    branches:
      - master

jobs:
  gdpr-check:
    runs-on: ubuntu-latest
    name: Validate GDPR Compliance
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run GDPR Check Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node check-gdpr.js
