name: GDPR Compliance Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  gdpr-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run GDPR Validation
        run: node check-gdpr.js
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

